---
- name: Download kube binaries
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ KUBERNETES_VERSION }}/bin/linux/amd64/{{ item }}"
    dest: "{{ localBuildOutput }}/{{ item }}"
    mode: 0755
  with_items:
    - kubelet
    - kube-proxy
    - kubectl

- name: Copy node binaries
  copy:
    src: "{{ localBuildOutput }}/{{ item }}"
    dest: /usr/bin/
    mode: 0755
  with_items:
    - kubelet
    - kube-proxy
    - kubectl
  notify:
    - restart daemons

- name: Copy node service files
  copy:
    src: ../init/systemd/{{ item }}
    dest: /etc/systemd/system/
    mode: 0644
  with_items:
    - kube-proxy.service
    - kubelet.service
  notify: reload systemd

- name: Copy node upstart files
  copy:
    src: ../init/upstart/{{ item }}
    dest: /etc/init
    mode: 0644
  with_items:
    - kubelet.conf
    - kube-proxy.conf
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 15

- name: Create the /var/lib/kubelet working directory
  file:
    path: /var/lib/kubelet
    state: directory
